server:
  address: 8080
spring:
  mvc:
    view:
      prefix: /pages/
      suffix: .jsp
  datasource:
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://106.14.191.232:3306/mini?characterEncoding=utf-8
      username: root
      password: root
    mybatis:
      type-aliases-package: com.itheima.domain
      configuration:
        map-underscore-to-camel-case: true
    logging:
      level:
        com.itheima: debug